StaticLibrary('libcommon',
    [
        Glob('/home/shenglish/workspace/FishServer/trunk/fish/libcommon/ConfReader/*.cpp'),
        Glob('/home/shenglish/workspace/FishServer/trunk/fish/libcommon/ThreadLog/*.cpp'),
        Glob('/home/shenglish/workspace/FishServer/trunk/fish/libcommon/FilterWord/*.cpp'),
        Glob('/home/shenglish/workspace/FishServer/trunk/fish/libcommon/Utils/*.cpp'),
        Glob('/home/shenglish/workspace/FishServer/trunk/fish/libcommon/RedisManager/*.cpp'),
        Glob('/home/shenglish/workspace/FishServer/trunk/fish/libcommon/protocol/*.cc'),
    ],
    CPPPATH = [
                '/home/shenglish/workspace/FishServer/trunk/fish',
                '/home/shenglish/workspace/FishServer/trunk/fish/libcommon/',
                '/home/shenglish/workspace/FishServer/trunk/fish/libcommon/Utils/',
                '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/thirdparty/include',
                '/home/shenglish/thirdparty/boost'
            ],
    LIBS = ['libboost_system',
            'libboost_thread',
            'libboost_filesystem',
            'libboost_date_time',
            'libboost_coroutine',
            'libboost_context',
            'libpthread',
            'libr3c',
            'libhiredis',
            'rt',
            'dl',
            'z'
        ],
    LINKFLAGS = '-static',
    LIBPATH = ['/usr/local/lib', '/usr/lib', '#/libcommon/RedisManager', '#/libcommon/hiredis','/home/shenglish/thirdparty/boost',
    '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/thirdparty/lib/hiredis'],
    CCFLAGS = '-g -DPOSIX -DNDEBUG -Wall -std=c++11'
)



Program('robot',
    [
        Glob('#/*.cpp'),
        Glob('#/connect/*.cpp'),
        Glob('#/behave/*.cpp'),
        Glob('#/Thread/*.cpp')
    ],
    CPPPATH = [
        '#/',
        '/usr/include',
        '#/../../FishServer/trunk/fish/GameServer/ModuleGame/Fish',
        '#/../../FishServer/trunk/fish/GameServer/ModuleConnection',
        '#/../../FishServer/trunk/fish/GameServer/Include',
        '#/../../FishServer/trunk/fish/GameServer',
        '#/../../FishServer/trunk/fish/libjsons',
        '#/../../FishServer/trunk/fish/libcommon',
        '#/../../FishServer/trunk/fish/libcommon/protocol',
        '#/../../FishServer/trunk/fish/libcommon/Utils',
        '#/../../FishServer/trunk/fish/libcommon/RedisManager',
        '#/../../../thirdparty/boost/',
        '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/RedisManager',
        '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/RedisManager/r3c',
        '/home/shenglish/workspace/Robot/MyRobotCor/connect'
    ],
    LIBS = ['libboost_system',
            'libboost_date_time',
            'libboost_filesystem',
            'libboost_regex',
            'libboost_serialization',
            'libboost_program_options',
            'libboost_coroutine',
            'libboost_context',
            'libcommon',
            'libprotobuf',
            'libssl',
            'libcrypto',
            'libboost_thread',
            'libpthread',
            'libr3c',
            'libhiredis',
            'libevent',
            'libicuuc',
            'libicudata',
            'rt',
            'dl',
            'z'
        ],
    LINKFLAGS = '-static',
    LIBPATH = ['/usr/lib/x86_64-linux-gnu',
                '/usr/local/lib',
                '/usr/lib',
                '/home/shenglish/thirdparty/boost',
                '#',
                '#/../../FishServer/trunk/fish',
                '#/../../FishServer/trunk/fish/libcommon/RedisManager',
                '#/../../FishServer/trunk/fish/libcommon/hiredis',
                '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/RedisManager',
                '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/thirdparty',
                '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/thirdparty/include',
                '/home/shenglish/workspace/FishServer/tags/20201119/trunk/src/libcommon/thirdparty/lib/hiredis'
            ],
    CCFLAGS = '-g -DPOSIX -DNDEBUG -O0 -Wall -DISABLE_PICOJSON -std=c++11 -DBOOST_COROUTINES_NO_DEPRECATION_WARNING'
)
